### ISSUE TITLE
API key is undefined?

### ISSUE THREAD

**Issue by dbounds** [aullman/OpenTok-Angular#9]
I'm getting a console message of: API Key is undefined. You must pass an API Key to initSession.

Yet I have the API key statically defined in the call to OTsession.init()

OTSession.init('STATICBUTHERE', $scope.interview.video_session_id, token, function (error, session) {});

**Comment by dbounds** [comment]
The error was actually the result of an invalid token, not a missing API key.

**Comment by JMacLulich** [comment]
I have the same issue, the error reporting is broken in the latest v2.5 opentok.js script. 

I was passing in an incorrect session id _not_ the ApiKey which led me on a wild goose chase for a while.

**Comment by aullman** [comment]
Actually this is because we're using a deprecated version of the API. The API changed to `OT.initSession(apiKey, sessionId);` and `session.connect(token)` but we're using the old `OT.initSession(sessionId)` and `session.connect(apiKey, token)`. This works thanks to backwards compatibility but it means the error messages are wrong.
